### ISSUE TITLE
[Crash]: Incompatibility with Combatify

### ISSUE THREAD

**Issue by Afrocntrik** [Fuzss/armorstatues#18] opened 2023-08-21 03:41 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.3

### Notes (Required)

Crash on initialization
Incompatibility with [Combatify](https://github.com/Alexandra-Myers/Combatify) more specifically with the Cookey Mod which is a library mod embedded in the .jar of Combatify.

### Crash Report (Required)

https://gist.github.com/Afrocntrik/568cb2b3d6a106aa986c397e4945b963

**Comment by Fuzss** [comment] 2023-08-21 07:16
Duplicate of https://github.com/Fuzss/puzzleslib/issues/67.

**Closed by Fuzss** 2023-08-21 07:16 UTC
Labels: bug
